app = 'ipay9-bot'
primary_region = 'sin'

[build]

[deploy]
  strategy = 'immediate'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python bot.py'

[[mounts]]
  source = 'ipay9_bot_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
